### ISSUE TITLE
To-do list (17/04 - 23/04)

### ISSUE THREAD

**Issue by beatrizmilz** [LatinR/web-LatinR2024#1]
## General
- [x] add logo

## Content

- [x] Add button to CFP
- [x] copy blog posts
- [ ] add newer blog posts on homepage
